runtime: php55
api_version: 1

handlers:
- url: /
  script: helloworld.php
  
- url: /app
  script: index3.php
  
- url: /index\.html
  script: home.php

- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /admin/.*
  script: admin.php
  login: admin

- url: /.*
  script: not_found.php
