runtime: php55
api_version: 1

handlers:
- url: /
  script: index3.php

- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /data.csv
  static_dir: data.csv

- url: /test.csv
  static_dir: test.csv
  
  
